name: C/C++ CI

on: [push]
  

jobs:
  check-bats-version:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compilation de server
      run: cd server
    - run: gcc server/pserver.c -o server/pserver
    - run: ./server/pserver
    - name: compilation de client
      run: cd client
    - run: gcc client/pclient.c -o client/pclient
    - run: ./client/pclient peg 0.0.0.0